import type { Product, Cart } from '@/types/shopify'

export const MOCK_PRODUCTS: Product[] = [
  // ─── Music ─────────────────────────────────────────────────────────────────
  {
    id: 'gid://shopify/Product/1',
    title: 'Back To Walking (Album Pre-Order)',
    handle: 'back-to-walking-album-pre-order',
    description: 'Pre-order the album Back To Walking by The Other Side of The Pen. Music & Sound Recordings.',
    productType: 'Music',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-album.jpg', altText: 'Back To Walking album cover', width: 800, height: 800 },
    images: [{ url: '/images/placeholder-album.jpg', altText: 'Back To Walking album cover', width: 800, height: 800 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/1',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/2',
    title: '"A Bullet Led Epiphany" Vol. I (Album Pre-Order)',
    handle: 'a-bullet-led-epiphany-vol-i-album-pre-order',
    description: 'Pre-order the album "A Bullet Led Epiphany" Vol. I by The Other Side of The Pen. Music & Sound Recordings.',
    productType: 'Music',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-album.jpg', altText: 'A Bullet Led Epiphany Vol. I album cover', width: 800, height: 800 },
    images: [{ url: '/images/placeholder-album.jpg', altText: 'A Bullet Led Epiphany Vol. I album cover', width: 800, height: 800 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/2',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/3',
    title: 'Raised Through Violence (Album Pre-Order)',
    handle: 'raised-through-violence-album-pre-order',
    description: 'Pre-order the album Raised Through Violence by The Other Side of The Pen. Music CDs.',
    productType: 'Music',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-album.jpg', altText: 'Raised Through Violence album cover', width: 800, height: 800 },
    images: [{ url: '/images/placeholder-album.jpg', altText: 'Raised Through Violence album cover', width: 800, height: 800 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/3',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/4',
    title: 'Hand to Hands (Album Pre-Order)',
    handle: 'hand-to-hands-album-pre-order',
    description: 'Pre-order the album Hand to Hands by The Other Side of The Pen. Music & Sound Recordings.',
    productType: 'Music',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-album.jpg', altText: 'Hand to Hands album cover', width: 800, height: 800 },
    images: [{ url: '/images/placeholder-album.jpg', altText: 'Hand to Hands album cover', width: 800, height: 800 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/4',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },

  // ─── Book ───────────────────────────────────────────────────────────────────
  {
    id: 'gid://shopify/Product/5',
    title: 'eBook (Pre-Order)',
    handle: 'ebook-pre-order',
    description: 'Pre-order the eBook by The Other Side of The Pen. E-Books.',
    productType: 'Book',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'eBook cover', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'eBook cover', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/5',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/6',
    title: 'Audiobook (Pre-Order)',
    handle: 'audiobook-pre-order',
    description: 'Pre-order the Audiobook by The Other Side of The Pen. Audiobooks.',
    productType: 'Book',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Audiobook cover', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Audiobook cover', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/6',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/7',
    title: 'Inscribed Edition (Pre-Order)',
    handle: 'inscribed-edition-pre-order',
    description: 'Pre-order the Inscribed Edition by The Other Side of The Pen. Print Books.',
    productType: 'Book',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Inscribed Edition cover', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Inscribed Edition cover', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/7',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/8',
    title: 'Hardcover Version (Pre-Order)',
    handle: 'hardcover-version-pre-order',
    description: 'Pre-order the Hardcover Version by The Other Side of The Pen. Print Books.',
    productType: 'Book',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Hardcover Version cover', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Hardcover Version cover', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/8',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/9',
    title: 'Paperback (Pre-Order)',
    handle: 'paperback-pre-order',
    description: 'Pre-order the Paperback by The Other Side of The Pen. Print Books.',
    productType: 'Book',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Paperback cover', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Paperback cover', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/9',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },

  // ─── Print ──────────────────────────────────────────────────────────────────
  {
    id: 'gid://shopify/Product/10',
    title: 'Inscribed Print II (Pre-Order)',
    handle: 'inscribed-print-ii-pre-order',
    description: 'Pre-order Inscribed Print II by The Other Side of The Pen. Prints.',
    productType: 'Print',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Inscribed Print II', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Inscribed Print II', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/10',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
  {
    id: 'gid://shopify/Product/11',
    title: 'Inscribed Print I (Pre-Order)',
    handle: 'inscribed-print-i-pre-order',
    description: 'Pre-order Inscribed Print I by The Other Side of The Pen. Prints.',
    productType: 'Print',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'Inscribed Print I', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'Inscribed Print I', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/11',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },

  // ─── Bundle ─────────────────────────────────────────────────────────────────
  {
    id: 'gid://shopify/Product/12',
    title: 'The 4/27 Edition (Pre-Order)',
    handle: 'the-4-27-edition-pre-order',
    description: 'Pre-order The 4/27 Edition bundle by The Other Side of The Pen. Bundles.',
    productType: 'Bundle',
    tags: ['preorder'],
    isPreorder: true,
    availableForSale: true,
    price: '0.00',
    compareAtPrice: null,
    currencyCode: 'USD',
    image: { url: '/images/placeholder-book.jpg', altText: 'The 4/27 Edition bundle', width: 800, height: 1000 },
    images: [{ url: '/images/placeholder-book.jpg', altText: 'The 4/27 Edition bundle', width: 800, height: 1000 }],
    variants: [
      {
        id: 'gid://shopify/ProductVariant/12',
        title: 'Default Title',
        availableForSale: true,
        quantityAvailable: 100,
        priceV2: { amount: '0.00', currencyCode: 'USD' },
        compareAtPriceV2: null,
        selectedOptions: [{ name: 'Title', value: 'Default Title' }],
      },
    ],
    hasSellingPlan: false,
  },
]

export const MOCK_CART: Cart = {
  id: 'mock-cart-id',
  checkoutUrl: 'https://theothersideofthepen.com/checkout',
  totalQuantity: 0,
  items: [],
  subtotal: '0.00',
  total: '0.00',
  currencyCode: 'USD',
}
